language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit

sudo: false

notifications:
  slack: asgardcms:oJ1NpQQ7t2vslPIlKzZHVvZE
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me

matrix:
  allow_failures:
    - php: hhvm
